export const PLANT_TAGS = {
    CAMPAIGN_TAGS: "Campaign Tags",
    BEST_SELLER: "Best Seller",
    NEW_LAUNCH: "New Launch",
    FEATURED: "Featured",
    TRENDING: "Trending",
    LIMITED_EDITION: "Limited Edition",
    BACK_IN_STOCK: "Back in Stock",
    CUSTOMER_FAVORITE: "Customer Favorite",
    COMBO_DEAL: "Combo Deal",
    FLASH_SALE: "Flash Sale",
    ADMIN_PICK: "Admin Pick"
};

export const TAG_URL_MAPPING = {
    "BEST_SELLER": PLANT_TAGS.BEST_SELLER,
    "NEW_LAUNCH": PLANT_TAGS.NEW_LAUNCH,
    "FEATURED": PLANT_TAGS.FEATURED,
    "TRENDING": PLANT_TAGS.TRENDING,
    "LIMITED_EDITION": PLANT_TAGS.LIMITED_EDITION,
    "BACK_IN_STOCK": PLANT_TAGS.BACK_IN_STOCK,
    "CUSTOMER_FAVORITE": PLANT_TAGS.CUSTOMER_FAVORITE,
    "COMBO_DEAL": PLANT_TAGS.COMBO_DEAL,
    "FLASH_SALE": PLANT_TAGS.FLASH_SALE,
    "ADMIN_PICK": PLANT_TAGS.ADMIN_PICK
};

export default PLANT_TAGS;